apiVersion: v1
kind: Secret
metadata:
  name: stargate-github-secret
  labels:
{{ include "stargate.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: "{{ .Values.githubSecret }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: stargate-gitlab-secret
  labels:
{{ include "stargate.labels" . | indent 4 }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: "{{ .Values.gitlabToken }}"
